# Generated by Django 5.2.4 on 2025-07-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_created_at_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='context',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='task',
        ),
        migrations.AddField(
            model_name='contextentry',
            name='name',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
