# Generated by Django 5.2.4 on 2025-07-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_task_deadline_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='context_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
